# Sync with _config.yml & _config_deploy.yml

markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
permalink: /:year/:month/:day/:title
pygments: true
exclude:
- Gemfile
- Gemfile.lock
- README.txt
- tidy.conf
- config.ru
- tasks
- public
- tmp
host: metaskills.net
deploying: true
